name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs every day at 0 a.m.
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog-posts-with-featured:
    name: Update this repo's README with latest blog posts with featured
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "FEATURED-POSTS"
          commit_message: "Updated readme with the latest blog posts with featured"
          feed_list: "https://oznote.io/feed.featured"

  update-readme-with-blog-posts:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "POSTS"
          commit_message: "Updated readme with the latest blog posts"
          feed_list: "https://oznote.io/feed"
